promotedai/promoted-ts-client

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: this changes the interface
> refactor: rename methods and variables

- README.md
- src/index.test.ts
- src/index.ts
Also updates a bunch of docs.
BREAKING CHANGE - this changes the interface
> feat: rename shouldOptimize to onlyLog

- jest.config.js
- src/client.test.ts
- src/client.ts
BREAKING CHANGE: this changes the external library interface
> feat: change prepareForLogging to be a sync method

- .gitignore
- README.md
- src/client.test.ts
- src/client.ts
- src/types/delivery.d.ts
BREAKING CHANGE: this removes limit and adds paging.
> feat: Add paging, deprecate limit;TESTING=unit

- package.json
- src/client.test.ts
- src/client.ts
WIP, for review of createLogRequest before I potentially refactor a lot of unit tests to verify the new method in various circumstances. Thanks.
> feat: createLogRequest function\rTESTING=unit

- .gitignore
- jest.config.js
- src/client.test.ts
- src/client.ts
- src/index.ts
- src/sampler.test.ts
- src/sampler.ts
- src/types/common.d.ts
- src/types/delivery.d.ts
- tsconfig.json
This is speculative based on the current design, minus the as-yet-undecided issue of how to handle paging. At any rate, this PR is probably large enough as-is and should be a no-op to existing clients.
> feat: First cut at shadow traffic support\rTESTING=unit

- README.md
- src/client-response.ts
- src/client.test.ts
- src/client.ts
- src/delivery-request.ts
- src/index.ts
- src/insertion-page-type.ts
- src/metrics-request.ts
- src/pager.test.ts
- src/pager.ts
@danbosnichill would you mind double-checking the logic and (especially) the names of things before I add tests? Thanks!
> feat: InsertionPageType on prepareForLogging\rTESTING=unit

- src/base-request.ts
- src/client.test.ts
- src/client.ts
- src/delivery-request.ts
- src/metrics-request.ts
This reduces the chance of clients breaking our SDK.
BREAKING CHANGE: this forces clients to change.  This will be a major version change.
TESTING=unit tests
> refactor: change compact*Insertion to compact*Properties

- src/client.ts
This is one of a bunch or commits to clarify the type of insertions.  This almost makes the compact function confusion even more obvious.
fixes PRO-492
TESTING=unit tests
> refactor: rename insertions to responseInsertion or requestInsertion

- README.md
> docs: add better docs around handleError

- README.md
> docs: update experiment docs

- src/index.ts
> Export hash.ts

- README.md
BREAKING CHANGE: see commit 6eae974200351d564e52b49aa163eae6fb19a41d for multiple breaking changes
TESTING=none
> feat: a commit to force a breaking change

- README.md
TESTING=copied from working code
> docs: fix axios doc bug

- src/client.ts
I seem to forget the semver messages, but in this case I also need to rev serverVersion.
> feat: Bump version for Browser.referrer field\rTESTING=unit

- src/client.test.ts
- src/client.ts
This reduces a manual step when debugging Errors in logs.
Also:
- Changes shadow traffic to use the same `deliveryTimeoutWrapper` as production.
- A small refactoring to improve test coverage.
Alternatives:
1. Do a breaking change to `handleError` by having a type for the error.
TESTING=unit tests
> feat: add clientrequestid to errors

- src/client.ts
> fix: the patch version

- README.md
TESTING=copy pasted code from working example
> docs: add httpsagent to the example

- src/client.ts
> fix: the string version

- README.md
> docs: add an advance experiment example

- README.md
> docs: add dns cache code snippet

- package.json
- src/client.ts
BREAKING CHANGE: putting this on this PR since the last one failed to build.
This PR also updates the version in package.json
> fix: build

- .github/workflows/publish_package.yml
fixes PRO-4335
Let's try bumping the version first.  I ran a version on a different branch and it might be okay.
https://github.com/promotedai/promoted-ts-client/actions/runs/4249968831/jobs/7390621364
> docs: try to fix semantic release gha

- README.md
- src/client-args.ts
- src/client.ts
- src/index.ts
- src/validator.test.ts
- src/validator.ts
> feat: support customizing validator arguments

- src/client.test.ts
I'm trying to debug an issue with the SDK.  This would execute the failure case.
TESTING=this.
> test: add a bad Delivery response test

- package.json
- rollup.config.js
- src/client.ts
I need to debug on a customer that uses Meteor which makes it hard to debug.  Removing terser will make it easier to step through code.
This also updates some package versions.
TESTING=none
> fix: remove terser

- src/client.ts
fixes PRO-4476
I broke this in my recent PR.
TESTING=run existing unit tests
> fix: blocking shadow traffic

- src/client.test.ts
- src/types/common.d.ts
- src/validator.test.ts
- src/validator.ts
PRO-5544
BREAKING CHANGE: renames an existing field.
TESTING=unit tests
> feat: rename logUserId to anonUserId

- .github/workflows/publish_package.yml
- .github/workflows/pull-requests_check.yml
> feat: update deps

- README.md
- src/client-args.ts
- src/client.ts
- src/index.ts
- src/validator.test.ts
- src/validator.ts
PRO-7523 - Improve promoted-ts-client
BREAKING CHANGE: The client interface is changing.
TESTING=ran automated tests
> fix: remove anonuserid validation; change validation args

- .releaserc.cjs
> fix: semantic release package.json location

- .github/workflows/publish_package.yml
- .github/workflows/pull-requests_check.yml
> chore: upgrade gha
